-- 코드를 입력하세요
SELECT DATE_FORMAT(O.SALES_DATE , '%Y') AS YEAR , DATE_FORMAT(O.SALES_DATE , '%m') AS MONTH , U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO U ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(O.SALES_DATE , '%Y') , DATE_FORMAT(O.SALES_DATE, '%m'), U.GENDER
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC