SELECT COUNT(*) AS FISH_COUNT, MAX(F.LENGTH) AS MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
GROUP BY F.FISH_TYPE
HAVING AVG(CASE WHEN F.LENGTH <= 10 THEN 10 ELSE F.LENGTH END) >= 33
ORDER BY FISH_TYPE ASC;